### ISSUE TITLE
Make Hex package

### ISSUE THREAD

**Issue by mworrell** [zotonic/z_stdlib#18]
Make a hex package for z_stdlib.

We should use the *Zotonic* user on hex.pm for this

@ddeboer has the keys :-)

/cc @arjan

**Comment by ddeboer** [comment]
Should we keep z_stdlib as the package name? We’ll have zotonic_core, zotonic_mod_acl_user_groups etc. for the core Zotonic packages. Perhaps zotonic_stdlib is an option (zotonic_z_stdlib looks silly :wink:).

**Comment by mworrell** [comment]
I am ok with `zotonic_stdlib`, it is very clear.

Then we also need to clone/fork the GitHub project.
Better leave an old z_stdlib behind, with some clear notes.

**Comment by ddeboer** [comment]
No need to move or fork the repo (though we can always do so later if we like it for consistency): this repo is now [automatically published] as zotonic_stdlib on Hex.pm when pushing a tag: https://hex.pm/packages/zotonic_stdlib.
