### ISSUE TITLE
no such file or directory, z_stdlib.app

### ISSUE THREAD

**Issue by basbz** [zotonic/z_stdlib#20]
Renaming from z_stdlib.app to zotonic_stdlib.app in
https://github.com/zotonic/z_stdlib/commit/2ed4b111f71a6da668681d589f3a4413d9b313b6#diff-7d3db80f7675121cb4b1dcb929b65516
seems to break the package:
```
Failed to boot z_stdlib for reason {"no such file or directory","z_stdlib.app"}
```

**Comment by mworrell** [comment]
@ddeboer what do you think?  Need to rename something back for now?

**Comment by mworrell** [comment]
ping @arjan

**Comment by ddeboer** [comment]
@mworrell What about locking our current (pre-OTP) Zotonic master and 0.x at the previous z_stdlib commit?

**Comment by ddeboer** [comment]
@basbz Are you running Zotonic or this library as a separate dependency?

**Comment by basbz** [comment]
@ddeboer we're using erlang_xlsx which has a dependcy on z_stdlib...
We've forked erlang_xlsx, and pinned z_stdlib on a previous commit.
So there's no real hurry 😅 
Is the general idea to rename the package?

**Comment by ddeboer** [comment]
@basbz Indeed! In fact, we’re making it easier as we just published this package to Hex: https://hex.pm/packages/zotonic_stdlib

Changing the name, however, is a breaking change. Libraries that depend z_stdlib should therefore either:
- lock the dep (I tagged a `0.1.0` legacy version of z_stdlib from before the name change)
- or change `{applications, [z_stdlib, …]}` to `{applications, [zotonic_stdlib, …]}` in their app.src.

**Comment by basbz** [comment]
Ok, sounds reasonable...
Thank you for your swift response.
