### ISSUE TITLE
Add HTML sanitizer from zotonic/mochiweb

### ISSUE THREAD

**Issue by mworrell** [zotonic/z_stdlib#23]
We depend on the zotonic/mochiweb version of the HTML sanitizer.

As that is the only (heavily) changed part of Mochiweb that we are using in Zotonic and in z_stdlib, I propose to copy that parser over to z_stdlib.

Then we can remove dependencies on non-standard mochiweb

/cc @ddeboer @mmzeeman

**Comment by mmzeeman** [comment]
👍 sounds like a good deal to me.

**Comment by mworrell** [comment]
This has been done.
