### ISSUE TITLE
z_svg filters legit svg style

### ISSUE THREAD

**Issue by pguyot** [zotonic/z_stdlib#38]
z_svg sanitizer relies on z_html sanitizer for style attribute, as a result attributes are often destroyed making svg images unusable on Zotonic.

Typically, the following tag:
````<rect x="0" y="0" width="213" height="101" style="fill:rgb(53.334045%,54.902649%,95.294189%);fill-opacity:0.5741;stroke:none;"/>````

is reduced to:
````<rect x="0" y="0" width="213" height="101" style=""></rect>````

**Comment by mworrell** [comment]
I guess we need to add some extra attributes to the whitelist of the css sanitizer.

I see here:

 * `fill`
 * `fill-opacity`
 * `stroke`

Any more?

**Comment by pguyot** [comment]
These SVG images also have ````fill-rule````, ```stop-color````, ````stop-opacity```` or ````opacity````. There probably is a list of valid attributes you may want to whitelist.

**Comment by mworrell** [comment]
Ah, found it, it is a problem with parsing of the floating point numbers. The lexer has a wrong definition.

**Comment by mworrell** [comment]
@pguyot #39 will fix your problem.

**Comment by mworrell** [comment]
Thanks for reporting the issue!

**Comment by mworrell** [comment]
Also merged into the 0.x branch
