### ISSUE TITLE
z_string:truncate crash

### ISSUE THREAD

**Issue by arjan** [zotonic/z_stdlib#53]
```
(zotonic001@x5)42> z_string:truncate(<<"æver at få lyd på">>, 10).
** exception error: no function clause matching z_string:truncate(<<"æver at få lyd på">>,10,
                                                                  <<226,128,166>>,
                                                                  in_word,<<>>,in_word,<<>>) (src/z_string.erl, line 791)
```

**Comment by mworrell** [comment]
Is the binary UTF-8 ?

**Comment by arjan** [comment]
I have not inspected it better yet, this came straight from an error log. `/admin/log` is unaccessible due to this error.. :-)

**Comment by arjan** [comment]
If you copy-paste this from the ticket it will crash again. It looks pretty valid to me..

**Comment by arjan** [comment]
https://apps.timwhitlock.info/unicode/inspect?s=%C3%A6ver+at+f%C3%A5+lyd+p%C3%A5

**Comment by mworrell** [comment]
I would expect this line to match the given pattern:

truncate(<<C/utf8,Rest/binary>>, N, Append, LastState, Last, _AccState, Acc) ->

Or am I overlooking something here?

**Comment by mworrell** [comment]
It is actually quite simple, binaries are Latin-1, unless marked with `/utf8`.

```erlang
<<"æver at få lyd på">>
```

is:

```erlang
[230,118,101,114,32,97,116,32,102,229,32,108,121,100,32,112,229]
```

and:

```erlang
<<"æver at få lyd på"/utf8>>
```

is:

```erlang
[195,166,118,101,114,32,97,116,32,102,195,165,32,108,121,100,32,112,195,165]
```

**Comment by mworrell** [comment]
The example should have been:

```erlang
z_string:truncate(<<"æver at få lyd på"/utf8>>, 10).
```

Which outputs:

```
<<195,166,118,101,114,32,97,116,226,128,166>>
```

**Comment by arjan** [comment]
Probably in `mod_logging` in `m_log_ui`.

**Comment by mworrell** [comment]
We could also drop all non-utf8 data from the string whilst truncating.

**Comment by arjan** [comment]
That is a more sensible approach I guess. At least don't crash on invalid data...
my binary pattern matching chops are a bit rusty though ;-)

**Comment by mworrell** [comment]
I will add a "drop of illegal characters" to the truncate 👍

**Comment by mworrell** [comment]
Are you running zotonic master or 0.x?  If your are on 0.x then I will also update the 0.x branch of z_stdlib

**Comment by mworrell** [comment]
z_stdlib 0.x and master are updated.

Monday I will release a new Zotonic 0.x version with the updated z_stdlib.
