### ISSUE TITLE
Lowercasing of accented characters

### ISSUE THREAD

**Issue by arjan** [zotonic/z_stdlib#55]
Is this supported?
```
(zotonic001@n5)4> z_string:to_lower(<<"é">>).
** exception error: no function clause matching z_string:to_lower(<<"é">>,<<>>) (src/z_string.erl, line 258)
```

**Comment by mworrell** [comment]
Yes, but try:

```erlang
z_string:to_lower(<<"é"/utf8>>).
```

Otherwise you might check latin-1.

**Comment by mworrell** [comment]
See also https://github.com/zotonic/z_stdlib/issues/53

**Comment by arjan** [comment]
aarghh :-) totally forgot about that ticket.

**Comment by mworrell** [comment]
They should make utf8 the default in the terminal... who uses latin-1 these days??
